name: dev
variables:
  - name: base_url
    value: http://localhost:8080
  - name: token
    value: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhNzJmMzFlZS0wOGMwLTQ3NGYtYjYwMi1mNGQ2OGNkZGY4MmIiLCJ1c2VybmFtZSI6Illha2VydSIsImlhdCI6MTc4MjE2NTMwNCwiZXhwIjoxNzgyMjUxNzA0fQ.8AvA-cQyb8aheOAo56KMErYwFS25033GdggnzcmbK47Kl8UgHycVWtsZCKuFaH9ja2ijVKUaRaVKurKy6Oig1g
  - name: project_id
    value: 42bd8027-e11b-4ff8-83a6-a6a6c07d2b61
  - name: task_id
    value: a0e96451-fecb-48c8-8af1-5d1f55a3c211
  - name: comment_id
    value: 1cf534d5-ae9a-48ba-9e04-e163c30b4575
